apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-cicd
spec:
  selector:
    matchLabels:
      app: service-cicd
  template:
    metadata:
      labels:
        app: service-cicd
    spec:
      containers:
        - name: service-cicd
          imagePullPolicy: Always
          image: izaakdale/service-cicd:v0.1.0
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-cicd
spec:
  selector:
    app: service-cicd
  ports:
    - port: 80
      targetPort: 80
