name: Publish Docker image

on:
  push:
    paths-ignore:
      - 'deploy/**'
      - '.github/**'
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: izaakdale/service-cicd:${{ steps.release.outputs.version }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: izaakdale/service-cicd:${{ steps.release.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'deploy/helm/service/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.release.outputs.version }}
          branch: deployment/${{ steps.release.outputs.version }}
          targetBranch: main
          createPR: true
          message: 'Update Image Version to ${{ steps.release.outputs.version }}'
